export default[{name:'Fridge', amount:0}, 
{name:'Diswasher', amount:0}, 
{name:'Washer', amount:0}, 
{name:'Drier', amount:0}, 
{name:'Closet', amount: 0}, 
{name:'Sofa', amount:0}, 
{name:'Bed', amount: 0}, 
{name:'Dinning Table', amount:0}, 
{name:'Mattress', amount:0}, 
{name:'Chair', amount:0}, 
{name:'Small boxes', amount:0}, 
{name:'Big boxes', amount:0}]